import { Metadata } from 'next';
import { fonts } from './chakra_ui/fonts';
import { Providers } from './chakra_ui/providers';
import Navigation from './components/Navigation';
import './globals.css';
export const metadata: Metadata = {
  title: 'Mental Health',
  description: 'Generated by create next app',
  icons: {
    icon: '/logoLink.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fonts.poppins.variable}>
      <body>
        <Providers>
          <Navigation />
          {children}
        </Providers>
      </body>
    </html>
  );
}
